import { Ruleset, RulesetReference } from '@simulacrum/common/ruleset'
import { Effects } from '@simulacrum/common'
import * as Fighter from '@simulacrum/rulesets/dnd-5e/class/class-fighter'
import * as FightingStyles from '@simulacrum/rulesets/dnd-5e/archetype/fighting-style'
import { FightingStyle } from '@simulacrum/rulesets/dnd-5e/archetype/fighting-style'
import * as WeaponMasteries from '@simulacrum/rulesets/dnd-5e/archetype/weapon-mastery'
import * as SkillProficiencies from '@simulacrum/rulesets/dnd-5e/archetype/skill-proficiency'
import { SkillProficiency } from '@simulacrum/rulesets/dnd-5e/archetype/skill-proficiency'
import * as Spells from '@simulacrum/rulesets/dnd-5e/archetype/spell'
import * as SkillExpertise from '@simulacrum/rulesets/dnd-5e/archetype/skill-expertise'
import * as ArtisansTools from '@simulacrum/rulesets/dnd-5e/archetype/artisans-tools'
import * as Tools from '@simulacrum/rulesets/dnd-5e/archetype/tool'
import * as Maneuvers from '@simulacrum/rulesets/dnd-5e/archetype/maneuver'
import * as Feats from '@simulacrum/rulesets/dnd-5e/archetype/feat'
import * as Backgrounds from '@simulacrum/rulesets/dnd-5e/archetype/background'
import * as AbilityScoreIncreases from '@simulacrum/rulesets/dnd-5e/archetype/ability-score-increase'
import * as Species from '@simulacrum/rulesets/dnd-5e/archetype/species'
import * as ClassArchetypes from '@simulacrum/rulesets/dnd-5e/archetype'
import * as Barbarian from '@simulacrum/rulesets/dnd-5e/class/class-barbarian'
import { CharacterOptions } from '@simulacrum/common/character'
import * as Cleric from '@simulacrum/rulesets/dnd-5e/class/class-cleric'
import * as Druid from '@simulacrum/rulesets/dnd-5e/class/class-druid'
import * as Bard from '@simulacrum/rulesets/dnd-5e/class/class-bard'
import * as Monk from '@simulacrum/rulesets/dnd-5e/class/class-monk'
import * as Paladin from '@simulacrum/rulesets/dnd-5e/class/class-paladin'
import * as Ranger from '@simulacrum/rulesets/dnd-5e/class/class-ranger'
import * as Rogue from '@simulacrum/rulesets/dnd-5e/class/class-rogue'
import * as Sorcerer from '@simulacrum/rulesets/dnd-5e/class/class-sorcerer'
import * as Warlock from '@simulacrum/rulesets/dnd-5e/class/class-warlock'
import * as Wizard from '@simulacrum/rulesets/dnd-5e/class/class-wizard'
import { CreatureCharacteristics, PlayerCharacteristics } from '@simulacrum/rulesets/dnd-5e/characteristic'
import { Dash, Disengage, Dodge, HealingSurge } from '@simulacrum/rulesets/dnd-5e/common'
import { HitPointResourcePool } from '@simulacrum/rulesets/dnd-5e/resource-pool'
import { CantripLoadout, PreparedSpellLoadout, WeaponMasteryLoadout } from '@simulacrum/rulesets/dnd-5e/loadout'

export const SelectClassLevel = CharacterOptions.selectTraitOption('select-class-level', { archetypes: [ClassArchetypes.Class] })

export const Dnd5e: Ruleset = {
  id: 'dnd-5e' as RulesetReference,
  name: 'Dungeons and Dragons 5e',
  creatureCharacteristics: Object.values(CreatureCharacteristics),
  playerCharacteristics: Object.values(PlayerCharacteristics),
  archetypes: [
    ClassArchetypes.Class,
    Backgrounds.Background,
    AbilityScoreIncreases.AbilityScoreIncrease,
    Species.Species,
    SkillProficiency,
    SkillExpertise.SkillExpertise,
    ArtisansTools.ArtisansTools,
    Tools.Tool,
    Tools.GamingSet,
    Tools.MusicalInstrument,
    FightingStyle,
    Fighter.FighterSubclass,
    Wizard.WizardSubclass,
    Cleric.ClericSubclass,
    Barbarian.BarbarianSubclass,
    Maneuvers.Maneuver,
    Feats.Feat,
    Feats.OriginFeat,
    ClassArchetypes.Cleric,
    ClassArchetypes.Wizard,
    Spells.Cantrip,
    Spells.Rank1,
    Spells.Rank2,
    Spells.Rank3,
    Spells.Abjuration,
    Spells.Conjuration,
    Spells.Divination,
    Spells.Enchantment,
    Spells.Evocation,
    Spells.Illusion,
    Spells.Necromancy,
    Spells.Transmutation,
  ],
  traits: [
    Barbarian.Level1,
    Bard.Level1,
    Cleric.Level1,
    Druid.Level1,
    Fighter.Level1,
    Fighter.WeaponMastery,
    Fighter.CombatSuperiority,
    Monk.Level1,
    Paladin.Level1,
    Ranger.Level1,
    Rogue.Level1,
    Sorcerer.Level1,
    Warlock.Level1,
    Wizard.Level1,
    Backgrounds.Acolyte,
    Backgrounds.Artisan,
    Backgrounds.Charlatan,
    Backgrounds.Criminal,
    Backgrounds.Entertainer,
    Backgrounds.Farmer,
    Backgrounds.Guard,
    Backgrounds.Guide,
    Backgrounds.Hermit,
    Backgrounds.Merchant,
    Backgrounds.Noble,
    Backgrounds.Sage,
    Backgrounds.Sailor,
    Backgrounds.Scribe,
    Backgrounds.Soldier,
    Backgrounds.Wayfarer,
    ...AbilityScoreIncreases.AbilityScoreTraits,
    ...Backgrounds.AbilityScoreIncreaseTraits,
    Species.Aasimar,
    Species.Small,
    Species.Medium,
    Species.Dragonborn,
    Species.Dwarf,
    Species.Elf,
    Species.Gnome,
    Species.Goliath,
    Species.Halfling,
    Species.Human,
    Species.Orc,
    Species.Tiefling,
    SkillProficiencies.Acrobatics,
    SkillProficiencies.AnimalHandling,
    SkillProficiencies.Arcana,
    SkillProficiencies.Athletics,
    SkillProficiencies.Deception,
    SkillProficiencies.History,
    SkillProficiencies.Insight,
    SkillProficiencies.Intimidation,
    SkillProficiencies.Investigation,
    SkillProficiencies.Medicine,
    SkillProficiencies.Nature,
    SkillProficiencies.Perception,
    SkillProficiencies.Performance,
    SkillProficiencies.Persuasion,
    SkillProficiencies.Religion,
    SkillProficiencies.SleightOfHand,
    SkillProficiencies.Stealth,
    SkillProficiencies.Survival,
    SkillExpertise.Acrobatics,
    SkillExpertise.AnimalHandling,
    SkillExpertise.Arcana,
    SkillExpertise.Athletics,
    SkillExpertise.Deception,
    SkillExpertise.History,
    SkillExpertise.Insight,
    SkillExpertise.Intimidation,
    SkillExpertise.Investigation,
    SkillExpertise.Medicine,
    SkillExpertise.Nature,
    SkillExpertise.Perception,
    SkillExpertise.Performance,
    SkillExpertise.Persuasion,
    SkillExpertise.Religion,
    SkillExpertise.SleightOfHand,
    SkillExpertise.Stealth,
    SkillExpertise.Survival,

    ArtisansTools.AlchemistsSupplies,
    ArtisansTools.BrewersSupplies,
    ArtisansTools.CalligraphersSupplies,
    ArtisansTools.CarpentersTools,
    ArtisansTools.CartographersTools,
    ArtisansTools.CobblersTools,
    ArtisansTools.CooksUtensils,
    ArtisansTools.GlassblowersTools,
    ArtisansTools.JewelersTools,
    ArtisansTools.LeatherworkersTools,
    ArtisansTools.MasonsTools,
    ArtisansTools.PaintersSupplies,
    ArtisansTools.PottersTools,
    ArtisansTools.SmithsTools,
    ArtisansTools.TinkersTools,
    ArtisansTools.WeaversTools,
    ArtisansTools.WoodcarversTools,
    Tools.DisguiseKit,
    Tools.ForgeryKit,
    Tools.HerbalismKit,
    Tools.NavigatorsTools,
    Tools.PoisonersKit,
    Tools.ThievesTools,
    Tools.DiceSet,
    Tools.DragonchessSet,
    Tools.PlayingCards,
    Tools.ThreeDragonAnteSet,
    Tools.Bagpipes,
    Tools.Drum,
    Tools.Dulcimer,
    Tools.Flute,
    Tools.Horn,
    Tools.Lute,
    Tools.Lyre,
    Tools.PanFlute,
    Tools.Shawm,
    Tools.Viol,
    Feats.AbilityScoreImprovement,
    Feats.Actor,
    Feats.Athlete,
    Feats.Charger,
    Feats.Chef,
    Feats.CrossbowExpert,
    Feats.Crusher,
    Feats.DefensiveDuelist,
    Feats.DualWielder,
    Feats.Durable,
    Feats.ElementalAdept,
    Feats.ElementalAdeptAcid,
    Feats.ElementalAdeptCold,
    Feats.ElementalAdeptFire,
    Feats.ElementalAdeptLightning,
    Feats.ElementalAdeptThunder,
    Feats.FeyTouched,
    Feats.Grappler,
    Feats.GreatWeaponMaster,
    Feats.HeavilyArmored,
    Feats.HeavyArmorMaster,
    Feats.InspiringLeader,
    Feats.KeenMind,
    Feats.LightlyArmored,
    Feats.MageSlayer,
    Feats.MartialWeaponTraining,
    Feats.MediumArmorMaster,
    Feats.ModeratelyArmored,
    Feats.MountedCombatant,
    Feats.Observant,
    Feats.Piercer,
    Feats.Poisoner,
    Feats.PolearmMaster,
    Feats.Resilient,
    Feats.RitualCaster,
    Feats.Sentinel,
    Feats.ShadowTouched,
    Feats.Sharpshooter,
    Feats.ShieldMaster,
    Feats.SkillExpert,
    Feats.Skulker,
    Feats.Slasher,
    Feats.Speedy,
    Feats.SpellSniper,
    Feats.Telekinetic,
    Feats.Telepathic,
    Feats.WarCaster,
    Feats.WeaponMaster,
    Feats.Alert,
    Feats.Crafter,
    Feats.Healer,
    Feats.Lucky,
    Feats.MagicInitiateCleric,
    Feats.MagicInitiateIntelligence,
    Feats.MagicInitiateWisdom,
    Feats.MagicInitiateCharisma,
    Feats.MagicInitiateDruid,
    Feats.MagicInitiateWizard,
    Feats.Musician,
    Feats.SavageAttacker,
    Feats.Skilled,
    Feats.TavernBrawler,
    Feats.Tough,
    FightingStyles.Archery,
    FightingStyles.BlindFighting,
    FightingStyles.Defense,
    FightingStyles.Dueling,
    FightingStyles.GreatWeaponFighting,
    FightingStyles.Interception,
    FightingStyles.Protection,
    FightingStyles.ThrownWeaponFighting,
    FightingStyles.TwoWeaponFighting,
    FightingStyles.UnarmedFighting,
    Fighter.Level2,
    Fighter.Level3,
    Barbarian.Level2,
    Barbarian.Level3,
    Barbarian.Level4,
    Barbarian.Level5,
    Barbarian.UnarmoredDefense,
    Barbarian.WeaponMastery,
    Barbarian.DangerSense,
    Barbarian.PrimalKnowledge,
    Barbarian.PathOfTheBerserker,
    Barbarian.Frenzy,
    Barbarian.PathOfTheWildHeart,
    Barbarian.AnimalSpeaker,
    Barbarian.RageOfTheWilds,
    Barbarian.PathOfTheWorldTree,
    Barbarian.VitalityOfTheTree,
    Barbarian.PathOfTheZealot,
    Barbarian.DivineFury,
    Barbarian.FastMovement,
    Bard.Level2,
    Bard.Level3,
    Bard.Level4,
    Bard.Level5,
    Cleric.Level2,
    Cleric.Level3,
    Cleric.Level4,
    Cleric.Level5,
    Cleric.Protector,
    Cleric.Thaumaturge,
    Cleric.ChannelDivinity,
    Cleric.SearUndead,
    Cleric.LifeDomain,
    Cleric.DiscipleOfLife,
    Cleric.LifeDomainSpells,
    Cleric.LifeDomainSpellsLevel5,
    Cleric.LightDomain,
    Cleric.LightDomainSpells,
    Cleric.LightDomainSpellsLevel5,
    Cleric.TrickeryDomain,
    Cleric.TrickeryDomainSpells,
    Cleric.TrickeryDomainSpellsLevel5,
    Cleric.WarDomain,
    Cleric.WarDomainSpells,
    Cleric.WarDomainSpellsLevel5,
    Druid.Level2,
    Druid.Level3,
    Druid.Level4,
    Druid.Level5,
    Fighter.Level4,
    Fighter.Level5,
    Monk.Level2,
    Monk.Level3,
    Monk.Level4,
    Monk.Level5,
    Paladin.Level2,
    Paladin.Level3,
    Paladin.Level4,
    Paladin.Level5,
    Ranger.Level2,
    Ranger.Level3,
    Ranger.Level4,
    Ranger.Level5,
    Rogue.Level2,
    Rogue.Level3,
    Rogue.Level4,
    Rogue.Level5,
    Sorcerer.Level2,
    Sorcerer.Level3,
    Sorcerer.Level4,
    Sorcerer.Level5,
    Warlock.Level2,
    Warlock.Level3,
    Warlock.Level4,
    Warlock.Level5,
    Wizard.Level2,
    Wizard.Level3,
    Wizard.Level4,
    Wizard.Level5,
    Wizard.Abjurer,
    Wizard.AbjurationSavant,
    Wizard.DivinationSavant,
    Wizard.EvocationSavant,
    Wizard.IllusionSavant,
    Wizard.AbjurationSavantRank3,
    Wizard.DivinationSavantRank3,
    Wizard.EvocationSavantRank3,
    Wizard.IllusionSavantRank3,
    Wizard.Diviner,
    Wizard.Evoker,
    Wizard.Illusionist,
    Fighter.BattleMaster,
    Fighter.Champion,
    Fighter.EldritchKnight,
    Fighter.PsiWarrior,
    Fighter.TacticalMind,
    Fighter.TacticalShift,
  ],
  abilities: [
    Maneuvers.Ambush,
    Maneuvers.BaitAndSwitch,
    Maneuvers.CommandersStrike,
    Maneuvers.CommandingPresence,
    Maneuvers.DisarmingAttack,
    Maneuvers.DistractingStrike,
    Maneuvers.EvasiveFootwork,
    Maneuvers.FeintingAttack,
    Maneuvers.GoadingAttack,
    Maneuvers.LungingAttack,
    Maneuvers.ManeuveringAttack,
    Maneuvers.MenacingAttack,
    Maneuvers.Parry,
    Maneuvers.PrecisionAttack,
    Maneuvers.PushingAttack,
    Maneuvers.Rally,
    Maneuvers.Riposte,
    Maneuvers.SweepingAttack,
    Maneuvers.TacticalAssessment,
    Maneuvers.TripAttack,
    ...WeaponMasteries.WeaponMasteries,
    Species.Darkvision,
    Species.CelestialResistance,
    Species.HealingHands,
    Species.CelestialRevelation,
    ...Spells.All,
    Dodge,
    Disengage,
    Dash,
    HealingSurge,
    Fighter.SecondWind,
    Fighter.ActionSurge,
    Fighter.ExtraAttack,
    Wizard.Spellcasting,
    Wizard.RitualAdept,
    Wizard.ArcaneRecovery,
    Wizard.ArcaneWard,
    Wizard.Portent,
    Wizard.PotentCantrip,
    Wizard.ImprovedIllusions,
    Wizard.MemorizeSpell,
    Barbarian.Rage,
    Barbarian.RecklessAttack,
    Barbarian.WarriorOfTheGods,
    Barbarian.ExtraAttack,
    Cleric.Spellcasting,
    Cleric.DivineSpark,
    Cleric.TurnUndead,
    Cleric.PreserveLife,
    Cleric.RadianceOfTheDawn,
    Cleric.WardingFlare,
    Cleric.BlessingOfTheTrickster,
    Cleric.InvokeDuplicity,
    Cleric.GuidedStrike,
    Cleric.WarPriest,
  ],
  resourcePools: [HitPointResourcePool, Cleric.ChannelDivinityPool, Maneuvers.SuperiorityDice],
  loadoutTypes: [CantripLoadout, PreparedSpellLoadout, WeaponMasteryLoadout],
  progressionTable: {
    1: [
      Effects.gainResourcePool(HitPointResourcePool),
      Effects.gainCharacterOption(SelectClassLevel),
      Effects.gainCharacterOption(Backgrounds.SelectBackground),
      Effects.gainCharacterOption(Species.SelectSpecies),
      Effects.gainAbility(Dodge),
      Effects.gainAbility(Disengage),
      Effects.gainAbility(Dash),
      Effects.gainAbility(HealingSurge),
      ...WeaponMasteries.gainWeaponMasteries(),
    ],
    2: [Effects.gainCharacterOption(SelectClassLevel)],
    3: [Effects.gainCharacterOption(SelectClassLevel)],
    4: [Effects.gainCharacterOption(SelectClassLevel)],
    5: [Effects.gainCharacterOption(SelectClassLevel)],
  },
}
