import { RulesetReference } from '@simulacrum/common/ruleset'
import { Ruleset } from '@simulacrum/common/ruleset'
import { Effects } from '@simulacrum/common'
import * as Fighter from '@simulacrum/rulesets/dnd-5e/class/class-fighter'
import * as FightingStyles from '@simulacrum/rulesets/dnd-5e/archetype/fighting-style'
import { FightingStyle } from '@simulacrum/rulesets/dnd-5e/archetype/fighting-style'
import * as WeaponMasteries from '@simulacrum/rulesets/dnd-5e/archetype/weapon-mastery'
import { WeaponMastery } from '@simulacrum/rulesets/dnd-5e/archetype/weapon-mastery'
import * as SkillProficiencies from '@simulacrum/rulesets/dnd-5e/archetype/skill-proficiency'
import { SkillProficiency } from '@simulacrum/rulesets/dnd-5e/archetype/skill-proficiency'
import * as ArtisansTools from '@simulacrum/rulesets/dnd-5e/archetype/artisans-tools'
import * as Maneuvers from '@simulacrum/rulesets/dnd-5e/archetype/maneuver'
import * as Feats from '@simulacrum/rulesets/dnd-5e/archetype/feat'
import { Class } from '@simulacrum/rulesets/dnd-5e/archetype'
import * as Barbarian from '@simulacrum/rulesets/dnd-5e/class/class-barbarian'
import { CharacterOptions } from '@simulacrum/common/character'
import * as Cleric from '@simulacrum/rulesets/dnd-5e/class/class-cleric'
import * as Druid from '@simulacrum/rulesets/dnd-5e/class/class-druid'
import * as Bard from '@simulacrum/rulesets/dnd-5e/class/class-bard'
import * as Monk from '@simulacrum/rulesets/dnd-5e/class/class-monk'
import * as Paladin from '@simulacrum/rulesets/dnd-5e/class/class-paladin'
import * as Ranger from '@simulacrum/rulesets/dnd-5e/class/class-ranger'
import * as Rogue from '@simulacrum/rulesets/dnd-5e/class/class-rogue'
import * as Sorcerer from '@simulacrum/rulesets/dnd-5e/class/class-sorcerer'
import * as Warlock from '@simulacrum/rulesets/dnd-5e/class/class-warlock'
import * as Wizard from '@simulacrum/rulesets/dnd-5e/class/class-wizard'
import { CreatureCharacteristics, PlayerCharacteristics } from '@simulacrum/rulesets/dnd-5e/characteristic'
import { Dash, Disengage, Dodge, HealingSurge } from '@simulacrum/rulesets/dnd-5e/common'
import { HitPointResourcePool } from '@simulacrum/rulesets/dnd-5e/resource-pool'

export const SelectClassLevel = CharacterOptions.selectTraitOption('afbef236-17a0-464f-b2d0-cb01ecf7931a', { archetypes: [Class] })

export const Dnd5e: Ruleset = {
  id: 'ca894259-d62d-4398-b417-cb4f0adf4ffe' as RulesetReference,
  name: 'Dungeons and Dragons 5e',
  creatureCharacteristics: Object.values(CreatureCharacteristics),
  playerCharacteristics: Object.values(PlayerCharacteristics),
  archetypes: [
    Class,
    SkillProficiency,
    ArtisansTools.ArtisansTools,
    FightingStyle,
    WeaponMastery,
    Fighter.FighterSubclass,
    Maneuvers.Maneuver,
    Feats.Feat,
  ],
  traits: [
    Barbarian.Level1,
    Bard.Level1,
    Cleric.Level1,
    Druid.Level1,
    Fighter.Level1,
    Monk.Level1,
    Paladin.Level1,
    Ranger.Level1,
    Rogue.Level1,
    Sorcerer.Level1,
    Warlock.Level1,
    Wizard.Level1,
    SkillProficiencies.Acrobatics,
    SkillProficiencies.AnimalHandling,
    SkillProficiencies.Arcana,
    SkillProficiencies.Athletics,
    SkillProficiencies.Deception,
    SkillProficiencies.History,
    SkillProficiencies.Insight,
    SkillProficiencies.Intimidation,
    SkillProficiencies.Investigation,
    SkillProficiencies.Medicine,
    SkillProficiencies.Nature,
    SkillProficiencies.Perception,
    SkillProficiencies.Performance,
    SkillProficiencies.Persuasion,
    SkillProficiencies.Religion,
    SkillProficiencies.SleightofHand,
    SkillProficiencies.Stealth,
    SkillProficiencies.Survival,
    ArtisansTools.AlchemistsSupplies,
    ArtisansTools.BrewersSupplies,
    ArtisansTools.CalligraphersSupplies,
    ArtisansTools.CarpentersTools,
    ArtisansTools.CartographersTools,
    ArtisansTools.CobblersTools,
    ArtisansTools.CooksUtensils,
    ArtisansTools.GlassblowersTools,
    ArtisansTools.JewelersTools,
    ArtisansTools.LeatherworkersTools,
    ArtisansTools.MasonsTools,
    ArtisansTools.PaintersSupplies,
    ArtisansTools.PottersTools,
    ArtisansTools.SmithsTools,
    ArtisansTools.TinkersTools,
    ArtisansTools.WeaversTools,
    ArtisansTools.WoodcarversTools,
    Maneuvers.Ambush,
    Maneuvers.BaitandSwitch,
    Maneuvers.CommandersStrike,
    Maneuvers.CommandingPresence,
    Maneuvers.DisarmingAttack,
    Maneuvers.DistractingStrike,
    Maneuvers.EvasiveFootwork,
    Maneuvers.FeintingAttack,
    Maneuvers.GoadingAttack,
    Maneuvers.LungingAttack,
    Maneuvers.ManeuveringAttack,
    Maneuvers.MenacingAttack,
    Maneuvers.Parry,
    Maneuvers.PrecisionAttack,
    Maneuvers.PushingAttack,
    Maneuvers.Rally,
    Maneuvers.Riposte,
    Maneuvers.SweepingAttack,
    Maneuvers.TacticalAssessment,
    Maneuvers.TripAttack,
    Feats.AbilityScoreImprovement,
    Feats.Actor,
    Feats.Athlete,
    Feats.Charger,
    Feats.Chef,
    Feats.CrossbowExpert,
    Feats.Crusher,
    Feats.DefensiveDuelist,
    Feats.DualWielder,
    Feats.Durable,
    Feats.ElementalAdept,
    Feats.FeyTouched,
    Feats.Grappler,
    Feats.GreatWeaponMaster,
    Feats.HeavilyArmored,
    Feats.HeavyArmorMaster,
    Feats.InspiringLeader,
    Feats.KeenMind,
    Feats.LightlyArmored,
    Feats.MageSlayer,
    Feats.MartialWeaponTraining,
    Feats.MediumArmorMaster,
    Feats.ModeratelyArmored,
    Feats.MountedCombatant,
    Feats.Observant,
    Feats.Piercer,
    Feats.Poisoner,
    Feats.PolearmMaster,
    Feats.Resilient,
    Feats.RitualCaster,
    Feats.Sentinel,
    Feats.ShadowTouched,
    Feats.Sharpshooter,
    Feats.ShieldMaster,
    Feats.SkillExpert,
    Feats.Skulker,
    Feats.Slasher,
    Feats.Speedy,
    Feats.SpellSniper,
    Feats.Telekinetic,
    Feats.Telepathic,
    Feats.WarCaster,
    Feats.WeaponMaster,
    FightingStyles.Archery,
    FightingStyles.BlindFighting,
    FightingStyles.Defense,
    FightingStyles.Dueling,
    FightingStyles.GreatWeaponFighting,
    FightingStyles.Interception,
    FightingStyles.Protection,
    FightingStyles.ThrownWeaponFighting,
    FightingStyles.TwoWeaponFighting,
    FightingStyles.UnarmedFighting,
    WeaponMasteries.Club,
    WeaponMasteries.Dagger,
    WeaponMasteries.Greatclub,
    WeaponMasteries.Handaxe,
    WeaponMasteries.Javelin,
    WeaponMasteries.LightHammer,
    WeaponMasteries.Mace,
    WeaponMasteries.Quarterstaff,
    WeaponMasteries.Sickle,
    WeaponMasteries.Spear,
    WeaponMasteries.Dart,
    WeaponMasteries.LightCrossbow,
    WeaponMasteries.Shortbow,
    WeaponMasteries.Sling,
    WeaponMasteries.Battleaxe,
    WeaponMasteries.Flail,
    WeaponMasteries.Glaive,
    WeaponMasteries.Greataxe,
    WeaponMasteries.Greatsword,
    WeaponMasteries.Halberd,
    WeaponMasteries.Lance,
    WeaponMasteries.Longsword,
    WeaponMasteries.Maul,
    WeaponMasteries.Morningstar,
    WeaponMasteries.Pike,
    WeaponMasteries.Rapier,
    WeaponMasteries.Scimitar,
    WeaponMasteries.Shortsword,
    WeaponMasteries.Trident,
    WeaponMasteries.Warhammer,
    WeaponMasteries.WarPick,
    WeaponMasteries.Whip,
    WeaponMasteries.Blowgun,
    WeaponMasteries.HandCrossbow,
    WeaponMasteries.HeavyCrossbow,
    WeaponMasteries.Longbow,
    WeaponMasteries.Musket,
    WeaponMasteries.Pistol,
    Fighter.Level2,
    Fighter.Level3,
    Barbarian.Level2,
    Barbarian.Level3,
    Barbarian.Level4,
    Barbarian.Level5,
    Bard.Level2,
    Bard.Level3,
    Bard.Level4,
    Bard.Level5,
    Cleric.Level2,
    Cleric.Level3,
    Cleric.Level4,
    Cleric.Level5,
    Druid.Level2,
    Druid.Level3,
    Druid.Level4,
    Druid.Level5,
    Fighter.Level4,
    Fighter.Level5,
    Monk.Level2,
    Monk.Level3,
    Monk.Level4,
    Monk.Level5,
    Paladin.Level2,
    Paladin.Level3,
    Paladin.Level4,
    Paladin.Level5,
    Ranger.Level2,
    Ranger.Level3,
    Ranger.Level4,
    Ranger.Level5,
    Rogue.Level2,
    Rogue.Level3,
    Rogue.Level4,
    Rogue.Level5,
    Sorcerer.Level2,
    Sorcerer.Level3,
    Sorcerer.Level4,
    Sorcerer.Level5,
    Warlock.Level2,
    Warlock.Level3,
    Warlock.Level4,
    Warlock.Level5,
    Wizard.Level2,
    Wizard.Level3,
    Wizard.Level4,
    Wizard.Level5,
    Fighter.BattleMaster,
    Fighter.Champion,
    Fighter.EldritchKnight,
    Fighter.PsiWarrior,
  ],
  abilities: [
    Dodge,
    Disengage,
    Dash,
    HealingSurge,
    Fighter.SecondWind,
    Fighter.ActionSurge,
    Fighter.TacticalMind,
    Fighter.ExtraAttack,
    Fighter.TacticalShift,
  ],
  resourcePools: [HitPointResourcePool],
  loadoutTypes: [],
  progressionTable: {
    1: [
      Effects.gainResourcePool(HitPointResourcePool),
      Effects.gainCharacterOption(SelectClassLevel),
      Effects.gainAbility(Dodge),
      Effects.gainAbility(Disengage),
      Effects.gainAbility(Dash),
      Effects.gainAbility(HealingSurge),
    ],
    2: [Effects.gainCharacterOption(SelectClassLevel)],
    3: [Effects.gainCharacterOption(SelectClassLevel)],
    4: [Effects.gainCharacterOption(SelectClassLevel)],
    5: [Effects.gainCharacterOption(SelectClassLevel)],
  },
}
