import { RulesetExtension, RulesetExtensionReference } from '@simulacrum/ruleset/ruleset'
import { Dnd5e } from '@simulacrum/ruleset-dnd5e'
import * as Artificer from '@simulacrum/ruleset-dnd5e/eberron-forge-of-the-artificer/class-artificer'
import * as MagicItemPlans from '@simulacrum/ruleset-dnd5e/eberron-forge-of-the-artificer/magic-item-plan'
import { HomunculusServant } from '@simulacrum/ruleset-dnd5e/eberron-forge-of-the-artificer/spell'

export const ForgeOfTheArtificer: RulesetExtension = {
  id: 'dnd-5e/eberron-forge-of-the-artificer' as RulesetExtensionReference,
  ruleset: Dnd5e.id,
  name: 'Eberron: Forge of the Artificer',
  creatureCharacteristics: [],
  playerCharacteristics: [],
  characteristicGroups: [],
  archetypes: [Artificer.ArtificerSubclass, MagicItemPlans.MagicItemPlan],
  traits: [
    Artificer.Level1,
    Artificer.Level2,
    Artificer.Level3,
    Artificer.Level4,
    Artificer.Level5,
    Artificer.Alchemist,
    Artificer.AlchemistToolsOfTheTrade,
    Artificer.AlchemistSpells,
    Artificer.AlchemistSpellsLevel5,
    Artificer.AlchemicalSavant,
    Artificer.Armorer,
    Artificer.ArmorerToolsOfTheTrade,
    Artificer.ArmorerSpells,
    Artificer.ArmorerSpellsLevel5,
    Artificer.ArmorModel,
    Artificer.ArmorerExtraAttack,
    Artificer.Artillerist,
    Artificer.ArtilleristToolsOfTheTrade,
    Artificer.ArtilleristSpells,
    Artificer.ArtilleristSpellsLevel5,
    Artificer.ArcaneFirearm,
    Artificer.BattleSmith,
    Artificer.BattleSmithToolsOfTheTrade,
    Artificer.BattleSmithSpells,
    Artificer.BattleSmithSpellsLevel5,
    Artificer.BattleReady,
    Artificer.BattleSmithLevel5,
    Artificer.Cartographer,
    Artificer.CartographerToolsOfTheTrade,
    Artificer.CartographerSpells,
    Artificer.CartographerSpellsLevel5,
    Artificer.GuidedPrecision,
    ...MagicItemPlans.Level2Plans,
  ],
  abilities: [
    HomunculusServant,
    Artificer.Spellcasting,
    Artificer.TinkersMagic,
    Artificer.ReplicateMagicItem,
    Artificer.ExperimentalElixir,
    Artificer.ArcaneArmor,
    Artificer.Dreadnaught,
    Artificer.Guardian,
    Artificer.Infiltrator,
    Artificer.EldritchCannon,
    Artificer.SteelDefender,
    Artificer.BattleSmithExtraAttack,
    Artificer.AdventurersAtlas,
    Artificer.IlluminatedCartography,
    Artificer.PortalJump,
  ],
  resourcePools: [],
  loadoutTypes: [Artificer.ArmorModelLoadout],
  progressionTable: {},
}
